**Домашнее задание 1**

Решите предложенные задания с использованием модуля NumPy. Использование условий и циклов крайне нежелательно (списковые включения это тоже цикл!), за это будут снижаться баллы.
Все задания равноценны. В каждой задаче постарайтесь придумать несколько решений. В задачах, где обязательно необходимо предложить хотя бы два решения, об этом написано. Решением должен быть Jupyter notebook / ссылка на Colab

Под массивом (если не указано иное), понимается одномерный массив. Для большей части задач не указан размер массива. Это значит, что код должен работать корректно для любого размера массива

1. Создайте массив 3x3, состоящий из True. Напишите минимум два варианта решения


In [ ]:
import numpy as np

print(np.array([[True, True, True], [True, True, True], [True, True, True]]))   #1 способ

A = np.full((3, 3), True)
print(A)                                                    #2 способ

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


2. Замените в массиве все нечетные положительные числа на -1

In [ ]:
x, y = map(int, input().split())                      #вводим необходимый размер массива
B = np.random.randint(-10, 10, (x, y))                #заполняем массив размера x * y рандомными числами от -10 до 10
print(B)

B[(B > 0) & (B % 2 == 1)] = -1                        #выполняем замену по условию
print(B)

3 3
[[ 6  1  1]
 [ 9 -7 -8]
 [ 4  9 -2]]
[[ 6 -1 -1]
 [-1 -7 -8]
 [ 4 -1 -2]]


3. Найдите все числа, встречающиеся в 1 и 2 массивах

In [ ]:
print(np.intersect1d(A, B))

[]


4. Дана функция maxx, работающая с двумя числами. Напишите обертку над ней, которая будет работать с двумя np.array (одинакового размера) и будет применять функцию maxx поэлементно (вместо maxx может быть любая другая кастомная функция)


```
def maxx(x, y):
	    return x if x >= y else y
```




In [ ]:
def maxx(x, y):
  return x if x >= y else y

A = np.random.randint(-10, 10, size = 10)
B = np.random.randint(-10, 10, size = 10)
C = []

for i in range(len(A)):
  C = np.append(C, maxx(A[i], B[i]))

print(A)
print(B)
print(C)

[-1 -6 -2  1 -4  2  4  7  3 -2]
[-4  8 -2  1 -1 -8  6  3  5  8]
[-1.  8. -2.  1. -1.  2.  6.  7.  5.  8.]


5. Дана матрица 3х3. Поменяйте местами 1 и 2 столбцы матрицы.

In [ ]:
A = np.random.randint(1, 10, (10, 10))
print(A)
A[:, [2, 1]] = A[:, [1, 2]]
print(A)

[[6 3 3 ... 8 9 3]
 [4 3 2 ... 9 4 6]
 [4 1 2 ... 8 6 8]
 ...
 [4 5 4 ... 3 9 8]
 [1 6 4 ... 1 5 4]
 [5 5 9 ... 1 6 7]]
[[6 3 3 ... 8 9 3]
 [4 2 3 ... 9 4 6]
 [4 2 1 ... 8 6 8]
 ...
 [4 4 5 ... 3 9 8]
 [1 4 6 ... 1 5 4]
 [5 9 5 ... 1 6 7]]


6. Поменяйте опции (```np.set_printoptions```), чтобы при выводе numpy.array отображалось не более 6 элементов

In [ ]:
np.set_printoptions(threshold = 6)
np.array(A)

array([[6, 3, 3, ..., 8, 9, 3],
       [4, 2, 3, ..., 9, 4, 6],
       [4, 2, 1, ..., 8, 6, 8],
       ...,
       [4, 4, 5, ..., 3, 9, 8],
       [1, 4, 6, ..., 1, 5, 4],
       [5, 9, 5, ..., 1, 6, 7]])

7. В данном массиве замените все числа, меньшие 0 на 0, а большие 255 на 255. Напишите минимум два варианта решения

In [ ]:
A = np.random.randint(-1000, 1000, (3, 3))
print(A)
A[(A < 0)] = 0            #1 способ
A[(A > 255)] = 255

np.clip(A, 0, 255)        #2 способ

print(A)

[[  10 -790  839]
 [-932  830  724]
 [-883 -795 -508]]
[[ 10   0 255]
 [  0 255 255]
 [  0   0   0]]


8. Выведите позиции топ-5 максимальных элементов в массиве. Попробуйте решить задачу за линейную сложность относительно числа элементов

In [ ]:
np.set_printoptions(threshold = 100)

D = np.random.randint(-10, 10, size=10)

print(D)

print(*D.argsort()[:4:-1])

[ 2 -8  3 -4  3 -2  2  4 -6 -9]
7 4 2 6 0


9. Преобразуйте массив массивов в одномерный массив.

In [ ]:
A = np.random.randint(-10, 10, [3, 3])
print(A)
print(A.ravel())

[[0 8 7]
 [1 6 5]
 [8 0 4]]
[0 8 7 1 6 5 8 0 4]


10. Найдите максимум в каждой строке двумерного массива

In [ ]:
A = np.random.randint(-10, 10, [3, 3])
print(A)
print(np.max(A, axis=1))

[[ 7  0 -2]
 [-1  6  1]
 [-3  4  5]]
[7 6 5]


11. Удалите все np.nan из массива

In [ ]:
A = np.array([[1, np.nan, 2], [np.nan, 3, np.nan], [4, np.nan, 5]])
print(A)

print(A[np.isnan(A) == False])

[[ 1. nan  2.]
 [nan  3. nan]
 [ 4. nan  5.]]
[1. 2. 3. 4. 5.]


12. Найдите индекс пятого повторения числа 1 в массиве (считаем, что в массиве есть хотя бы пять единиц)

In [ ]:
A = np.array([1, 1, 2, 1, 3, 1, 4, 1, 5])
print(np.where(A == 1)[0][4])

7


13. В квадратной матрице 5х5 из нулей получить ромб из 1, который касается середин сторон квадрата. Решите задачу как для полного ромба (внутри все 1), так и для полого (1 по границе, внутри 0):

```
полный           полый
0 0 1 0 0       0 0 1 0 0
0 1 1 1 0       0 1 0 1 0
1 1 1 1 1       1 0 0 0 1
0 1 1 1 0       0 1 0 1 0
0 0 1 0 0       0 0 1 0 0
```

In [ ]:
A = np.array([[0] * 5] * 5)
B = np.array([[0] * 5] * 5)
for i in range(5):
  for j in range(5):
    if i == 2 or ((i == 1 or i == 3) and (j < 4 and j > 0)) or ((i == 0 or i == 4) and (j == 2)): #рисуем полный ромб
      A[i][j] = 1
    if (i == 2 and (j == 0 or j == 4)) or ((i == 1 or i == 3) and (j == 1 or j == 3)) or ((i == 0 or i == 4) and (j == 2)): #рисуем полый ромб
      B[i][j] = 1

print(A)
print(B)

[[0 0 1 0 0]
 [0 1 1 1 0]
 [1 1 1 1 1]
 [0 1 1 1 0]
 [0 0 1 0 0]]
[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]


14. Создать случайную матрицу 5x7 целых чисел от 1 до 100 и удалить [3,5] колонки

In [ ]:
A = np.random.randint(1, 100, [5, 7])
print(A)
A = np.delete(A, [2, 4], 1)
print(A)

[[36 92 87 14 38 57 89]
 [29 33 26 26 64 85 12]
 [80 40 95 45 93 25 22]
 [56 18 70 74  7 60 26]
 [20 22 55 61 38 59 33]]
[[36 92 14 57 89]
 [29 33 26 85 12]
 [80 40 45 25 22]
 [56 18 74 60 26]
 [20 22 61 59 33]]


15. Вычислите [скользящее среднее](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%BE%D0%BB%D1%8C%D0%B7%D1%8F%D1%89%D0%B0%D1%8F_%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D1%8F%D1%8F) в окне ширины 3

In [ ]:
A = np.random.randint(1, 10, size = 15)
A = np.sort(A)
window = 3

i = 0
itog = []

while i < len(A) - window + 1:
    q = round(np.sum(A[i:i + window]) / window, 2)
    itog.append(q)
    i += 1

print(itog)

[2.33, 3.0, 3.33, 3.67, 4.0, 4.0, 4.33, 5.0, 6.0, 6.67, 7.33, 8.0, 8.67]
